Update merge_master_to_staging_and_qa.yml

diff --git a/.github/workflows/merge_master_to_staging_and_qa.yml b/.github/workflows/merge_master_to_staging_and_qa.yml
--- a/.github/workflows/merge_master_to_staging_and_qa.yml
+++ b/.github/workflows/merge_master_to_staging_and_qa.yml
@@ -41,7 +41,7 @@ jobs:
       run: |
         git fetch origin
         git checkout staging
-        git merge master || { echo "Merge conflict in staging, aborting"; exit 1; }
+        git pull origin master --rebase || { echo "Merge conflict in staging, aborting"; exit 1; }
         git push origin staging || { echo "Failed to push to staging"; exit 1; }
 
     - name: Merge master into qa
@@ -49,5 +49,5 @@ jobs:
       run: |
         git fetch origin
         git checkout qa
-        git merge master || { echo "Merge conflict in qa, aborting"; exit 1; }
+        git pull origin master --rebase || { echo "Merge conflict in qa, aborting"; exit 1; }
         git push origin qa || { echo "Failed to push to qa"; exit 1; }
